language: python

#which versions of python to test against
python:
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - pip install codecov
  - pip install coverage

#  - pip install ./lecture7/
#  - pip install -r ./lecture7/requirements.txt, done

script:
  - python -m unittest discover -v ./testfiles/ # command to run unit test, done
  - coverage run ./testfiles/test.py # command to run code coverage, done

#can do additional things, say send out reports, which we will discuss next time
after_success:
  - codecov --token=cd54358e-e6e7-44fa-ae8b-2c9ce3ac4c00 # upload coverage report to codecov.io, done

deploy:
  provider: s3
  access_key_id: AKIAJQWMFU4EQ7QJEN6A #populate with your own AWS access key
  secret_access_key: w0uTrNLGtTjqzArT4Ntv/ZqLIiJ94YyQ+EIypIRn #populate with your own AWS secret key
  bucket: balinbanh-cps847.com
  local-dir: assignment2
  region: canada-central-
